# PostgreSQL
#   Ensure the PostgreSQL gem is defined in your Gemfile
#   gem 'pg'
development:
  adapter: postgresql
  encoding: utf8
  database: csv_importer_development
  username: root
  host: localhost
  pool: 5
  port: 5432
  password: root
